Repository P5-wrapper/react, pull requests merged in 2021-09, with the labels that each got.

#113 Update the example with the latest changes
  example/index.html
Labels: enhancement

#112 Update dependencies and readme docs
  README.md
  example/app.jsx
  example/sketches/box.js
  example/sketches/torus.js
  package-lock.json
  package.json
Labels: dependencies, documentation

#115 Updating broken example in readme
  README.md
  package-lock.json
Labels: documentation

#120 Updating dependencies to latest versions
  package-lock.json
  package.json
Labels: dependencies

#121 Resolve prettier warning output
  config/prettier.config.js
Labels: dependencies

#119 Add documentation for Typescript and resolve typing issues
  README.md
  package-lock.json
  package.json
Labels: dependencies, documentation
