Repository P5-wrapper/react, pull requests merged in 2021-06, with the labels that each got.

#96 Update dependencies to fix vulnerabilities
  jest.config.js
  package-lock.json
  package.json
Labels: dependencies

#99 Create SECURITY.md
  SECURITY.md
Labels: enhancement, security

#98 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#100 Update integration scripts
  .github/workflows/PR.yml
  .github/workflows/Push.yml
  .github/workflows/ci.yml
  SECURITY.md
  package-lock.json
Labels: enhancement

#101 Convert to functional style and expose more types for the upcoming version 3 release
  .babelrc
  .eslintrc
  .gitignore
  .npmignore
  LICENSE
  README.md
  example/src/app.jsx
  example/src/index.html
  example/src/sketches/sketch.js
  example/src/sketches/sketch2.js
  package-lock.json
  package.json
  rollup.config.js
  src/index.tsx
  tests/__snapshots__/index.test.tsx.snap
  tests/index.test.tsx
  tsconfig.json
  webpack.config.demo.js
Labels: dependencies, enhancement

#93 Remove redundant dotfiles
  .eslintignore
  .npmignore
  .prettierrc
  package.json
Labels: dependencies, enhancement

#103 Fix Format Script
  package.json
Labels: bug

#106 Cleanup configurations and update dependencies
  .babelrc
  .editorconfig
  .eslintrc
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/SECURITY.md
  .github/SUPPORT.md
  .github/workflows/CODEQL.yml
  .github/workflows/Push.yml
  .gitignore
  .prettierignore
  config/.eslintrc.js
  config/jest.config.js
  config/rollup.config.js
  config/tsconfig.json
  config/webpack.config.demo.js
  example/app.jsx
  example/example.css
  example/index.html
  example/sketches/sketch.js
  example/sketches/sketch2.js
  jest.config.js
  package-lock.json
  package.json
  src/index.tsx
  tests/__fixtures__/sketch.ts
  tests/index.test.tsx
  webpack.config.demo.js
Labels: dependencies, enhancement, security

#102 Update prettier config and update code
  .github/SECURITY.md
  .github/SUPPORT.md
  README.md
  config/eslint.config.js
  config/prettier.config.js
  config/webpack.config.js
  docs/eslint.md
  docs/prettier.md
  example/app.jsx
  example/sketches/sketch.js
  example/sketches/sketch2.js
  package.json
  src/index.tsx
Labels: enhancement
