Repository P5-wrapper/react, pull requests merged in 2022-01, with the labels that each got.

#133 Bundle size improvements
  config/rollup.config.js
  example/index.html
  package-lock.json
  package.json
  src/index.tsx
Labels: enhancement, dependencies

#135 Update dependencies
  package-lock.json
  package.json
Labels: dependencies, security

#137 Add new example of declaring sketch
  README.md
Labels: documentation

#139 Prepare version 3.1.0 release
  package-lock.json
  package.json
Labels: dependencies, documentation

#141 Update SECURITY.md supported versions
  .github/SECURITY.md
Labels: security, documentation
