Repository P5-wrapper/react, pull requests merged in 2022-08, with the labels that each got.

#178 Audit dependencies
  config/typescript/tsconfig.json
  package.json
  pnpm-lock.yaml
  src/index.tsx
  tests/helpers/streams.ts
  tests/rendering.test.tsx
Labels: enhancement, dependencies, security

#177 Type updates and runtime error handling
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .github/workflows/CODEQL.yml
  config/eslint/eslint.config.js
  config/typescript/tsconfig.json
  package.json
  pnpm-lock.yaml
  src/index.tsx
  tests/helpers/streams.ts
  tests/rendering.test.tsx
  tests/updates.test.tsx
Labels: enhancement, help wanted, documentation

#180 Fix for demo deployments in the CD workflow
  .github/workflows/CD.yml
  package.json
  pnpm-lock.yaml
Labels: bug, dependencies, documentation

#181 Auto deploy to NPM in CD workflow
  .github/workflows/CD.yml
Labels: enhancement, dependencies, documentation

#182 Upgrade demo to React 18
  example/app.jsx
Labels: enhancement
